name: Check 
on: [pull_request]
jobs:

  get-cargo-dirs:
    outputs:
      dirs: ${{ steps.dirs.outputs.dirs }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get all Cargo.toml files in the project
        id: dirs
        run:
          echo '::set-output name=dirs::[' $(find . -name 'Cargo.toml' | tr '\n' ', ') ']'

  cargo-deny:
    runs-on: ubuntu-latest
    needs: get-cargo-dirs
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
        dirs: ${{needs.get-cargo-dirs.dirs}}

    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
    - name: "Checkout code"
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'force-skip-ci') && ( success() || failure() ) }}
      uses: actions/checkout@v2
    - name: "Check Rust Licenses"
      uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: check ${{ matrix.checks }}
        entrypoint: ${{ matrix.dirs }}